package: ffmpeg: Drop outdated synth_filter_vfp.S extra source
This file is present in ffmpeg sources since version 2.1 already and due
to internal changes, it wont link anymore (undefined reference to
ff_imdct_half_c). Just drop it.

Signed-off-by: Phil Sutter <phil@nwl.cc>