package/radvd: Update to version 2.18
The old version didn't get along with newer kernel headers, got error
messages like:

[...]/linux/if_arp.h:116:8: error: redefinition of 'struct arpreq'

Signed-off-by: Phil Sutter <phil@nwl.cc>